import { Phrases } from '../types';

const phrases: Phrases = {
  1: 'Someone is wearing a unique shirt',
  2: '"I think what you said is..."',
  // 3: '“lots of love in the comments"',
  4: '“I wish we had more time”',
  // 5: 'Someone has a unique virtual background',
  6: 'Any astrology reference',
  // 7: '“Put your questions in the comments”',
  8: 'Meeting finishes on time',
  9: 'Someone breaks out into dance',
  // 10: '“Can you hear me now?',
  11: '“A little bit about me"',
  12: 'Cough or sneeze',
  13: '“Pride”',
  // 14: 'You spot a pet',
  15: "“What's your career?”​",
  // 16: '“Can you see my screen?”​',
  // 17: '“Thank you for joining us”',
  // 18: 'Someone one uses the pride flag emoji',
  19: '“On the main stage”',
  20: '“Our next speaker is…"',
  21: '“Before we start”',
  // 22: 'Speaker was on mute',
  23: 'Verbal description of themselves',
  24: "“I'd like to introduce...”​",
  25: 'Coffee mug',
  26: 'Pride Flag',
  27: '“Give it up for…”',
  28: "Someone's 1st time at LWT event",
  29: 'Meet someone new',
  30: 'LWT intro video',
  31: 'Music',
  32: 'LWT swag spotted',
  // 33: 'Select the “Connect” button in Speed Networking',
  34: '“Join us next year”',
  35: 'Learn something new about tech',
  36: 'Talk to someone in your field',
  37: 'Dancing',
  38: `Got someone's LinkedIn`,
  39: 'Someone mentions Squad Jobs',
  40: 'Text someone about LWT',
  41: 'See a wedding ring',
  42: 'Someone complements another person',
  43: 'Find someone you know',
  // 44: 'Real background',
  45: 'Make a new friend',
  46: 'Talk to someone starting their career',
  47: 'Strategic initiative',
  // 48: 'Technical difficulties during speed networking',
  49: 'Speaker describes how they look',
  50: '"Astrology"',
  // 51: 'Someone uses the clapping emoji in the chat',
  52: 'Spot an Aquarius',
  53: 'Spot a Pisces',
  54: 'Spot an Aries',
  55: 'Spot a Taurus',
  56: 'Spot a Gemini',
  57: 'Spot a Cancer',
  58: 'Spot a Leo',
  59: 'Spot a Virgo',
  60: 'Spot a Libra',
  61: 'Spot a Scorpio',
  62: 'Spot a Sagittarius',
  63: 'Spot a Capricorn',
  64: '"A.I."',
  65: '"Artificial Intelligence"',
  66: 'Did you learn something new?',
  67: 'Learn an attendee`s pet`s name',
  68: 'Connect with InCo on Instagram',
  69: '"Queer. Inclusive. Badass."',
  70: 'Connect with a speaker on LinkedIn',
  71: '"Generative A.I."',
  72: '"Bonus Question"',
  73: '"It`s wonderful to be back"',
  74: 'Connect with a UXer',
  75: 'Connect with a product manager',
  76: 'Chat with a software engineer',
  77: 'Follow LWT on Instagram',
  78: '"Take it away ___"',
  // 79: 'Send the speaker a clapping emoji in the chat',
  // 80: '"11th annual"',
  81: '"Thank you for your time"',
  82: '"Cloud computing"',
  83: '"Inclusivity"',
  84: 'Attend a keynote',
  85: 'Attend summit main stage kick-off',
  //86: 'Attend a summit welcome presentation',
  87: '"Thank you for having me"',
  88: 'Attend a networking session',
  89: 'Chat with a cybersecurity person',
  90: 'Find someone who loves games',
  91: 'Find folx who have attended 2+ events',
  92: 'Find folx who have a startup',
  93: 'Spot a tech related t-shirt @ LWT',
  94: 'Linkup with someone new to tech',
  95: 'Link up with a tech transitioner',
  96: 'Find an AI ethics enthusiast',
  97: 'Link up with a 10+ year techie',
  98: 'Presenter shares a coming-out story',
  99: 'Participant shares their queer icon',
  // 100: 'Supportive messages flood in for a brave question',
  101: 'Participant shares a queer book rec',
  // 102: 'Encouragement given to participant for first time comment',
  103: 'Presenter shares inclusive media',
  104: 'Presenter ends with love',
  105: 'Shares you queer business fav',
  106: 'Presenter shares queer non-profit fav',
  107: 'Someone shares pro dev tips',
  108: 'Someone shares a self-love moment',
  // 109: 'Notice a speaker wearing headphones',
  // 110: 'Speaker has an interesting piece of art in their background',
  111: 'See someone celebrate a bingo!',
  // 112: 'Speaker uses Pride themed slides!',
  113: 'See a speaker wave hello or goodbye',
  114: 'Speaker mentions fav tech gadget',
  115: 'Follow LWT on LinkedIn',
  116: 'Follow Inco on LinkedIn',
  117: 'Explore the InCo website',
  118: 'Share your bingo & tag InCo',
  119: 'Like others` bingo on social media',
  120: 'Post about the LWT conference',
  121: 'Tell your friends about this game!',
  // 122: 'Ask a questions in the chat',
  123: 'Set up your conference profile',
  124: 'Add an image to your LWT profile',
  125: 'Add your socials to your LWT profile',
  126: 'Attend all days of the summit',
  127: 'Listen to the LWT Spotify playlist',
  // 128: 'Get yourself a hot drink',
  129: 'Wear something Pride related',
  // 130: 'Get some fresh air',
  // 131: 'Spend 5 minutes with your fur baby',
  132: 'Send your friend a positive message',
  // 133: 'Send someone a positive emoji in the chat',
  // 134: 'Put your LinkedIn in the chat',
  135: 'Add another participant on LinkedIn',
  136: 'Sign up for the next LWT conference',
  137: 'You own more than 5 Pride items',
  // 138: 'Stretch a little',
  139: 'Find a queer author`s book',
  140: 'Visit `Get Involved` on InCo site',
  141: 'Send us your bingo card ideas!',
  142: 'Send bingo game comments on socials',
  143: 'Speaker discusses intersectionality',
  144: 'Presenter shares their queer journey',
  145: 'See a carabiner',
  // 146: 'Georgia O`Keefe artwork',
  // 147: 'Bookshelf behind a speaker',
  148: 'Connect with an Inco team member',
  149: 'Tech company swag sighting',
  150: 'DIY networking spreadsheet created',
  // 151: 'Cactus or succulent plant sighting',
  152: 'Has a non-traditional tech background',
  153: 'Hear a new (to you) acronym',
  // 154: 'Ask a question in the chat/Q&A',
  155: 'Check out someone`s portfolio/website',
  // 156: 'Answer someone`s question in the chat',
  // 157: 'Drink water!',
  // 158: 'Get a snack',
  159: 'Look at a company`s Careers page',
  160: 'Talk to a recruiter',
  161: 'Denim jacket',
  162: 'Post about attending LWT Summit on LI',
  163: 'Check out the Inco site',
  164: 'Read an article written by a speaker',
  165: 'Add Olivia Servaes from InCo on LI',
  166: 'Add Lane Hamilton from InCo on LI',
  167: 'Add Liz Baranowicz from InCo on LI',
  168: 'Add Tegan Barron from InCo on LI',
  169: 'Add Jimena Cuadros from InCo on LI',
  170: 'Add Lynds Lesh from InCo on LI',
  171: 'Add Olivia McCartney from InCo on LI',
  172: 'Add Juliane Cassidy from InCo on LI',
  173: 'Add Chelsea Snider from InCo on LI',
  174: 'Add Wei Lim from InCo on LI',
  175: 'Add Amy Ashmore from InCo on LI',
  176: 'Add K.D. Hubbard from InCo on LI',
  177: 'Add Alex Sharp from InCo on LI',
  // 178: 'Add a comment in the chat',
  179: 'Comment on a LWT post',
  180: 'Comment on an InCo post',
  // 181: 'Someone shares a session from a past LWT Summit',
  182: 'Presenter shares Queer projects',
  183: 'Some shares their favorite speaker',
  184: 'Presenter shares fav Queer role model',
  185: 'Learn from someone else`s question',
  186: 'Learn about being Queer in bootcamps',
  187: 'Cheer for the impact of LWT on tech',
  188: 'Attend at least 3 sessions',
  189: 'Attend a full day of sessions',
  190: 'Star session you want to go to',
  191: 'Somebody mentions last year`s bingo',
  // 192: 'Watch a recording of a presentation',
  193: 'Presenter is wearing a tie',
  194: 'Presenter is wearing a blazer',
  195: 'Presenter is wearing a cardigan',
  // 196: 'Presenter does not use slides',
  197: 'Talk about the LWT summit at work',
  198: 'Get a friend to play bingo with you',
  199: 'Be a Queer Badass!',
  200: 'Checkout the LWT YouTube',
  201: 'Be proud!',
  202: '"Welcome to LWT 12"',
  203: '"Welcome to our Queer inclusive squad"',
  204: '"Welcome badass leaders"',
  205: '"My code is non-binary"',
  206: '"share knowledge"',
  // 207: 'Post about your at home conference setup',
  208: 'Find your friends at the conference',
  209: 'Visit a sponsor',
  210: 'Sign up a friend for the summit',
  211: 'Presenter is wearing a collared shirt',
  212: 'Presenter has tattoos',
  213: 'Visit a speaker`s profile',
  // 214: 'Go to a meetup chat',
  215: '"inclusive"',
  216: 'Order a LWT t-shirt',
  217: 'Order a LWT cup',
  218: 'Order a LWT sticker',
  219: 'Order a LWT sweatshirt',
  220: 'Visit Jobs on LWT',
  221: 'Visit the InCo About Us page',
  222: 'Visit the InCo FAQ page',
  223: 'Get 3 bingos!',
  224: 'Get 4 bingos!',
  225: 'Get 5 bingos!',
  226: 'Get 2 bingos!',
  227: 'You own a bingo dobber',
  228: '"you`ve played Bingo as a kid"',
  229: '"You`ve played Gay bingo"',
  230: '"You`ve played Drag bingo"',
  // 231: '"feel free to ask any questions in the chat"',
  232: '"don`t hesitate to reach out"',
  233: '"thank you for participating & engaging"',
  234: 'Post with #LWTSQUAD',
  235: 'Post with #LWTSUMMIT',
  236: 'Post with #BingoWithInCo',
  237: '"as we wrap it up"',
  238: '"green technologies"',
  239: '"quantum computing"',
  240: 'I am a presenter',
  241: 'Taylor Swift reference is made',
  242: 'Chappell Roan reference is made',

  //new phrases for 2024
  3: 'Check out Bozoma Saint John session',
  5: 'Check out Sophia Bush session',
  7: 'Check out Heather Freeland session',
  10: 'Check out Sue Bird session',
  14: 'Check out Megan Rapinoe session',
  16: 'Check out Kara Swisher session',
  17: 'Check out Tekedra N. Mawakana session',
  18: 'Danced to music at a booth',
  22: 'Take a funny selfie with a new friend',
  33: 'Found someone with the same name',
  44: 'Shared a joke with a stranger',
  48: 'High-fived people at the conference',
  51: 'Play a mini-game with someone',
  79: 'Participate in a mini flash mob',
  80: 'Make your own mini flash mob',
  86: 'Add Brandi Ude from InCo on LI',
  100: 'Collected the most unsual swag item',
  102: 'Got a unique sticker for your laptop',
  109: 'Find a booth giving out candy',
  110: 'Joined a coding challenge',
  112: 'Shared a tech joke with someone',
  122: 'Locate a Pride flag',
  128: 'Locate a Trans flag',
  130: 'Eat street food',
  131: 'Visit Brooklyn Bridge',
  133: 'Visit Chinatown',
  134: 'Visit Wall Street',
  138: 'Eat Pizza',  
  146: 'Experience a Checker cab',
  147: 'Make friends with a subway rat',
  151: 'Experience a Yellow Cab',
  154: 'See the Statue of Liberty',
  156: 'Expereince Time Square',
  157: 'Visit Central Park',
  158: 'Visit the Flatiron Building',
  178: 'Explore an art museum',
  181: 'Visit St. Mark`s Place',
  192: 'Ride the Staten Islan ferry',
  196: 'Explore New York Public Library',
  207: 'Visit the High Line',
  214: 'Visit Grand Central Station',
  231: 'Visit the Cloisters',  
  243: 'Get some conference swag',
  244: 'Update your career goals',
  245: 'Get inspired by a speaker',
  246: 'Catch up with an old friend',
  247: 'Attend any event',
  248: 'Plan your schedule',
  249: 'Shared a conference moment in emojis',
  250: 'Eat something delicious',
  251: 'Post on social media about an event',
  252: 'Follow a speaker on social media',
  253: 'Live-tweet an event',
  254: 'Create an event-related meme',
  255: 'Decorate your name badge',
  256: 'Decorate an item with swag',
  257: 'Met someone from a different country',
  258: 'Exchanged business cards',
  259: 'Networked during a break',
  260: 'Collected a conference swag item',
  261: 'Took a selfie with a speaker',
  262: 'Wore conference badge the entire day',
  263: 'Received an email from an exhibitor',
  264: 'Scheduled a post-conference meeting',
  265: 'Won a prize in a giveaway',
  266: 'Collected 5+ business cards',
  267: 'Sat in the front row of a session',
  268: 'Signed up for a newsletter',
  269: 'Discussed a potential collaboration',
  270: 'Took notes during a session',
  271: 'Introduced yourself to a speaker',
  272: 'Sat next to someone you didn`t know',
  273: 'Found a job opportunity',
  274: 'Volunteered at the event',
  275: 'Took a break in the lounge area',
  276: 'Experience the Sponser Booths',
  277: 'Explore Pier 16',
  278: 'Learn about LWT Coding Scholarship',
  279: 'Learn about LWT C3 Work program',
  280: 'Scan sponsor`s QR code',
  281: 'Follow sponsor on social media',
  282: 'Share this game with a sponsor',
  283: 'Share this game with an attendee',
  284: 'Learn about a sponsor`s products',
  285: 'Introduce yourself to a sponsor',
  286: 'Exchange info with a sponsor rep',
  287: 'Ask a sponsor about job openings',
  288: 'Ask a sponsor about industry trends',
  289: 'Comment on a sponsor`s media post',
  290: 'Share a sponsor`s post on LinkedIn',
  291: 'Thank a sponsor for their support',
  292: 'Tag the sponsor in an Instagram story',
  293: 'Send an email thanking the sponsor',
  294: 'Add InCo on LinkedIn',
  295: 'Add InCo on Facebook',
  296: 'Add InCo on Instagram',
  297: 'Create a post about InCo',
  298: 'Meet someone from InCo',
  299: 'Post with #InCoBingo',
  300: 'Leave a positive review for InCo',
  301: 'Post a photo of you playing Bingo',
  302: 'Follow InCo`s social media',
  303: 'Like an InCo post',
  304: 'Tag a friend who would love InCo',
  305: 'Post a story mentioning InCo',
  306: 'Refer a friend to follow InCo`s page',
  307: 'Comment on InCo`s post with an emoji',
  308: 'Follow InCo on all our social media',
  309: 'Explore LWT careers',
  310: 'Sign up for 2025 Pride Summit',
  311: 'Explore the Lawn Club',
  312: 'Explore the Tin Building',
  313: 'Explore the Seaport Plaza',
  314: 'Explore the Rooftop @ Pier 17',
  315: 'Play Cornhole at LWT',
  316: 'Play Basketball at LWT',
  317: 'Hangout @ the picnic tables',
  318: 'Catch up @ Livestream Park',
  319: 'Access the LWT schedule',
  320: 'Explore Sports Park',
  321: 'Explore the Main Stage',
  322: 'Explore the Breakout Stages',
  323: 'Access the Tech Crawl',
  324: 'Wear a crazy pair of socks',
  325: 'Joined an impromptu karaoke session',
  326: 'Start a conga line',
  327: 'Took a goofy group photo',
  328: 'Found someone who can do a cool trick',
  329: 'Have someone draw a caricature of you',
  330: 'Doodled on a napkin',
  331: 'Traded swag items with someone',
  332: 'Spotted a Kalama Harris t-shirt',
  333: 'Created a funny name tag for yourself',
  334: 'Someone says `Lesbians Who Tech`',
  335: 'An attendee breaks out into dance',
  336: 'Created a conference-inspired dance',
  337: 'Play Rock, Paper, Scissors',
  338: 'Found someone with a great pet story',
  339: 'Find someone wearing a jean jacket',
  340: 'You own a Bingo Dauber',
  341: 'Connect with a speaker',
  342: 'Did you learn something new?',
  343: 'Take a 10-minute meditation break',
  344: 'Enjoyed a healthy snack',
  345: 'Listened to your favorite music',
  346: 'Had a screen-free hour',
  347: 'Take a coffee break',
  348: 'Add Miranda Sajdak from InCo on LI',
};

export default phrases;
