import { Phrases } from '../types';

const phrases: Phrases = {
  1: 'Someone is wearing a unique shirt',
  2: '"I think what you said is..."',
  // 3: '“lots of love in the comments"',
  3: 'Join Bozoma Saint John`s session',
  4: '“I wish we had more time”',
  5: 'Join Sophia Bush`s session',
  // 5: 'Someone has a unique virtual background',
  6: 'Any astrology reference',
  7: 'Join Heather Freeland`s session',
  8: 'Add Miranda Sajdak from InCo on LI',
  // 7: '“Put your questions in the comments”',
  //8: 'Meeting finishes on time',
  9: 'Someone breaks out into dance',
  // 10: '“Can you hear me now?',
  10: 'Attend Sue Bird`s session',
  11: '“A little bit about me"',
  12: 'Take a coffee break',
  13: '“Pride”',
  // 14: 'You spot a pet',
  14: 'Attend Megan Rapinoe`s session',
  15: "“What's your career?”​",
  16: 'Attemd Kara Swisher`s session',
  17: 'Join Tekedra N. Mawakana`s session',
  18: 'Dance to booth music',
  // 16: '“Can you see my screen?”​',
  // 17: '“Thank you for joining us”',
  // 18: 'Someone one uses the pride flag emoji',
  19: '“On the main stage”',
  20: '“Our next speaker is…"',
  21: '“Before we start”',
  22: 'Take a group selfie',
  23: 'Have a screen-free hour',
  // 22: 'Speaker was on mute',
  //23: 'Verbal description of themselves',
  24: "“I'd like to introduce...”​",
  25: 'Experience a Coffee cup',
  26: 'Pride Flag',
  27: '“Give it up for…”',
  28: "Someone's 1st time at LWT event",
  29: 'Meet someone new',
  30: 'Take a music break',
  //30: 'LWT intro video',
  31: 'Music',
  32: 'LWT swag spotted',
  33: 'Find someone with the same name',
  // 33: 'Select the “Connect” button in Speed Networking',
  34: '“Join us next year”',
  35: 'Learn something new about tech',
  36: 'Talk to someone in your field',
  37: 'Dancing',
  38: `Get someone's LinkedIn`,
  39: 'Someone mentions Squad Jobs',
  40: 'Text someone about LWT',
  41: 'See a wedding ring',
  42: 'Someone compliments someone else',
  43: 'Find someone you know',
  44: 'Share a joke with a stranger',
  // 44: 'Real background',
  45: 'Make a new friend',
  46: 'Meet someone new to tech',
  47: '"Strategic initiative"',
  48: 'High-five someone!',
  // 48: 'Technical difficulties during speed networking',
  49: 'Speaker describes how they look',
  50: '"Astrology"',
  51: 'Play a game with someone',
  // 51: 'Someone uses the clapping emoji in the chat',
  52: 'Spot an Aquarius',
  53: 'Spot a Pisces',
  54: 'Spot an Aries',
  55: 'Spot a Taurus',
  56: 'Spot a Gemini',
  57: 'Spot a Cancer',
  58: 'Spot a Leo',
  59: 'Spot a Virgo',
  60: 'Spot a Libra',
  61: 'Spot a Scorpio',
  62: 'Spot a Sagittarius',
  63: 'Spot a Capricorn',
  64: '"A.I."',
  65: '"Artificial Intelligence"',
  66: 'Learn something new',
  67: 'Learn someone`s pet`s name',
  68: 'Follow @interconnectedco on IG',
  69: '"Queer. Inclusive. Badass."',
  70: 'Connect with a speaker on LinkedIn',
  71: '"Generative A.I."',
  72: '"Bonus Question"',
  73: '"It`s wonderful to be back"',
  74: 'Connect with a UXer',
  75: 'Connect with a product manager',
  76: 'Connect with a software engineer',
  77: 'Follow @LWTech on IG',
  78: '"Take it away ___"',
  79: 'Participate in a flash mob',
  80: 'Create a flash mob',
  // 79: 'Send the speaker a clapping emoji in the chat',
  // 80: '"11th annual"',
  81: '"Thank you for your time"',
  82: '"Cloud computing"',
  83: '"Inclusivity"',
  84: 'Attend a keynote',
  85: 'Attend Kick-Off',
  86: 'Add Brandi Ude from InCo on LI',
  //86: 'Attend a summit welcome presentation',
  87: '"Thank you for having me"',
  88: 'Attend a networking session',
  89: 'Chat with a cybersecurity person',
  90: 'Find a gamer',
  91: 'Find a repeat LWT attendee',
  92: 'Find a startup employee',
  93: 'Spot a tech pun t-shirt',
  94: 'Meet someone new to tech',
  95: 'Meet a tech career changer',
  96: 'Talk about AI ethics with someone',
  97: 'Chat with a 10+ year techie',
  98: 'Hear a coming-out story',
  99: '"Queer icon"',
  100: 'Collect an unsual swag item',
  // 100: 'Supportive messages flood in for a brave question',
  101: 'Get a queer book recommendation',
  102: 'Get a new sticker for your laptop',
  // 100: 'Supportive messages flood in for a brave question',
  // 102: 'Encouragement given to participant for first time comment',
  103: 'Presenter shares inclusive media',
  104: 'Presenter ends with love',
  105: 'Promote a queer business',
  106: 'Presenter mentions fav non-profit',
  107: 'Someone shares pro dev tips',
  108: 'Someone shares a self-love moment',
  109: 'Find a booth giving out candy',
  110: 'Join a coding challenge',
  // 109: 'Notice a speaker wearing headphones',
  // 110: 'Speaker has an interesting piece of art in their background',
  111: 'See someone get a Bingo!',
  112: 'Share a tech joke with someone',
  // 112: 'Speaker uses Pride themed slides!',
  113: 'Speaker waves hello or goodbye',
  114: 'Speaker mentions a tech gadget',
  115: 'Follow LWT on LinkedIn',
  116: 'Follow Inco on LinkedIn',
  117: 'Explore the InCo website',
  118: 'Share your Bingo & tag us!',
  119: 'Like an InCo Bingo post on LinkedIn',
  120: 'Post about LWT Summit',
  121: 'Tell a friend about InCo Bingo!',
  122: 'Spot a Pride flag',
  // 122: 'Ask a questions in the chat',
  123: 'Set up your LWT Summit profile',
  124: 'Add a photo to your LWT profile',
  125: 'Add socials to your LWT profile',
  126: 'Attend all days of the Summit',
  127: 'Listen to LWT Spotify playlist',
  128: 'Spot a Trans flag',
  // 128: 'Get yourself a hot drink',
  129: 'Wear a Pride item',
  130: 'Eat street food',
  131: 'Visit the Brooklyn Bridge',
  // 130: 'Get some fresh air',
  // 131: 'Spend 5 minutes with your fur baby',
  132: 'Send a positive message to someone',
  133: 'Visit Chinatown',
  134: 'Visit Wall Street',
  // 128: 'Get yourself a hot drink',
  // 130: 'Get some fresh air',
  // 131: 'Spend 5 minutes with your fur baby',
  // 133: 'Send someone a positive emoji in the chat',
  // 134: 'Put your LinkedIn in the chat',
  135: 'Add an attendee on LI',
  136: 'Register for the next LWT event',
  137: 'Spot 5+ Pride items',
  138: 'Eat pizza',
  // 138: 'Stretch a little',
  139: 'Find a queer author`s book',
  140: 'Visit "Get Involved" InCo page',
  141: 'Suggest a Bingo card!',
  142: 'Post about InCo Bingo',
  143: '"Intersectionality"',
  144: 'Presenter shares their "journey"',
  145: 'See a carabiner',
  146: 'Make a funny name tag',
  147: 'Befriend a subway rat',
  // 146: 'Georgia O`Keefe artwork',
  // 147: 'Bookshelf behind a speaker',
  148: 'Connect with an Inco team member',
  149: 'See tech company swag',
  150: 'Add to a networking spreadsheet',
  151: 'Spot a Yellow Cab',
  // 151: 'Cactus or succulent plant sighting',
  152: 'Meet a non-traditional techie',
  153: 'Learn a new acronym',
  154: 'See the Statue of Liberty',
  // 154: 'Ask a question in the chat/Q&A',
  155: 'View someone`s portfolio',
  156: 'Visit Times Square',
  157: 'Visit Central Park',
  158: 'Visit the Flatiron Building',
  // 156: 'Answer someone`s question in the chat',
  // 157: 'Drink water!',
  // 158: 'Get a snack',
  159: 'Visit a Sponsor`s Careers page',
  160: 'Talk to a recruiter',
  161: 'Spot a denim jacket',
  162: 'Post about LWT Summit on LinkedIn',
  163: 'Visit the InCo site',
  164: 'Read a speaker`s article',
  165: 'Add Olivia Servaes from InCo on LI',
  166: 'Add Lane Hamilton from InCo on LI',
  167: 'Add Liz Baranowicz from InCo on LI',
  168: 'Add Tegan Barron from InCo on LI',
  169: 'Add Jimena Cuadros from InCo on LI',
  170: 'Add Lynds Lesh from InCo on LI',
  171: 'Have a healthy snack',
  //171: 'Add Olivia McCartney from InCo on LI',
  172: 'Add Juliane Cassidy from InCo on LI',
  173: 'Add Chelsea Snider from InCo on LI',
  174: 'Add Wei Lim from InCo on LI',
  175: 'Add Amy Ashmore from InCo on LI',
  176: 'Add K.D. Hubbard from InCo on LI',
  177: 'Add Alex Sharp from InCo on LI',
  178: 'Visit an art museum or gallery',
  // 178: 'Add a comment in the chat',
  179: 'Comment on a LWT post',
  180: 'Comment on an InCo post',
  181: 'Visit St. Mark`s Place',
  // 181: 'Someone shares a session from a past LWT Summit',
  182: 'Presenter shares a side project',
  183: 'Post about your favorite speaker',
  184: 'Speaker shares a queer role model',
  185: 'Learn from someone`s questions',
  186: 'Learn about a bootcamp',
  187: 'Audience cheers',
  188: 'Attend 3+ sessions',
  189: 'Attend a full day of sessions',
  190: 'Add sessions to your Summit Agenda',
  191: 'Hear someone mention Bingo',
  192: 'Ride the Staten Island ferry',
  // 192: 'Watch a recording of a presentation',
  193: 'Presenter has on a tie',
  194: 'Presenter has on a blazer',
  195: 'Presenter has on a cardigan',
  196: 'Visit the New York Public Library',
  // 196: 'Presenter does not use slides',
  197: 'Mention LWT at work',
  198: 'Get a friend to play Bingo',
  199: 'Be a Queer Inclusive Badass!',
  200: 'Visit the LWT YouTube',
  201: 'Be proud!',
  202: '"Welcome to Lesbians Who Tech 12"',
  203: 'Take a meditation break',
  //203: '"Welcome to our Queer inclusive squad"',
  204: '"Badass leader(s)"',
  205: '"My code is non-binary"',
  206: '"Share knowledge"',
  207: 'Visit the High Line',
  // 207: 'Post about your at home conference setup',
  208: 'Find your friends at the Summit',
  209: 'Visit a sponsor booth',
  210: 'Refer a friend to LWT',
  211: 'Spot a collared shirt',
  212: 'Presenter has visible tattoos',
  213: 'Visit a speaker`s LWT profile',
  // 214: 'Go to a meetup chat',
  214: 'Visit Grand Central Station',
  215: '"Inclusive"',
  216: 'Order/shop for a LWT t-shirt',
  217: 'Order/shop for a LWT cup',
  218: 'Order/shop for a LWT sticker',
  219: 'Order/shop for a LWT sweatshirt',
  220: 'Visit LWT "Careers" page',
  221: 'Visit the InCo About Us page',
  222: 'Visit the InCo FAQ page',
  223: 'See someone dance',
  224: 'Ask someone to draw a doodle of you',
  225: 'Ask about someone`s fun fact',
  226: 'Talk to a speaker',
  //223: 'Get 3 bingos!',
  //224: 'Get 4 bingos!',
  //225: 'Get 5 bingos!',
  //226: 'Get 2 bingos!',
  227: 'You`ve own a Bingo dauber',
  228: 'You`ve played Bingo IRL before',
  229: 'You`ve played Queer Bingo before',
  230: 'You`ve played Drag Bingo before',
  231: 'Visit the Cloisters',
  // 231: '"feel free to ask any questions in the chat"',
  232: '"Reach out"',
  233: '"Thanks for participating"',
  234: 'Post with #LWTSQUAD',
  235: 'Post with #LWTSUMMIT',
  236: 'Play rock, paper, scissors',
  //236: 'Post with #BingoWithInCo',
  237: '"As we wrap it up..."',
  238: '"Green technologies"',
  239: '"Quantum computing"',
  240: 'Tell a pet story',
  //240: 'I am a presenter',
  241: 'Taylor Swift reference',
  242: 'Chappell Roan reference',
  243: 'Get Summit swag',
  244: 'Update your career goals',
  245: 'Get inspired by a speaker',
  246: 'Catch up with an old friend',
  247: 'Attend any event',
  248: 'Plan your Summit schedule',
  //249: 'Shared a conference moment in emojis',
  249: '"Lesbians Who Tech"',
  250: 'Eat something delicious!',
  251: 'Post about LWT',
  252: 'Follow a speaker`s socials',
  253: 'Live-tweet an event',
  254: 'Create a meme',
  255: 'Decorate your Summit badge',
  256: 'Wear some swag!',
  257: 'Meet someone from another country',
  258: 'Exchange business cards or emails',
  259: 'Network during a break',
  260: 'Snag some swag!',
  261: 'Selfie with a speaker',
  262: 'Wear LWT badge all day',
  263: 'Sign up for an exhibitor`s emails',
  264: 'Book a post-Summit meeting',
  265: 'Enter a giveaway',
  266: 'Collect 5+ business cards',
  267: 'Sit front row for a session',
  268: 'Sign up for a newsletter',
  269: 'Talk about a collaboration idea',
  270: 'Take session notes',
  271: 'Say hello to a speaker',
  272: 'Sit next to a stranger',
  273: 'Find a cool job opportunity',
  274: 'Say hello to a volunteer',
  275: 'Visit the Executive Lounge',
  276: 'Check out Sponser Booths',
  277: 'Explore Pier 17',
  278: 'Read about LWT Coding Scholarship',
  279: 'Read about LWT C3 Work Program',
  280: 'Scan a QR code',
  281: 'Follow a sponsor`s social media',
  282: 'Share Bingo with a sponsor',
  283: 'Share this game with an attendee',
  284: 'Learn about a sponsor`s products',
  285: 'Meet a sponsor',
  286: 'Exchange info with a sponsor rep',
  287: 'Ask a sponsor about job openings',
  288: 'Ask about industry trends',
  289: 'Comment on a sponsor`s media post',
  290: 'Share a sponsor`s post on LinkedIn',
  291: 'Thank a sponsor',
  292: 'Tag a sponsor',
  293: 'Email a sponsor',
  294: 'Follow InCo on LinkedIn',
  295: 'Add InCo on Facebook',
  296: 'Add InCo on Instagram',
  297: 'Create a post about InCo',
  298: 'Meet someone from InCo',
  299: 'Post with #InCoBingo',
  300: 'Leave a review for InCo',
  301: 'Post a photo playing Bingo',
  302: 'Follow InCo`s social media',
  303: 'Like an InCo post',
  304: 'Tag a friend who`d love InCo',
  305: 'Post a story mentioning InCo',
  306: 'Refer a friend to InCo',
  307: 'Comment on InCo post with an emoji',
  308: 'Follow InCo on all our socials',
  309: 'Explore LWT careers',
  310: 'Sign up for 2025 Pride Summit',
  311: 'Explore the Lawn Club',
  312: 'Explore the Tin Building',
  313: 'Explore the Seaport Plaza',
  314: 'Explore the Rooftop @ Pier 17',
  315: 'Play cornhole at LWT',
  316: 'Play basketball at LWT',
  317: 'Hangout @ the picnic tables',
  318: 'Catch up @ Livestream Park',
  319: 'Access the LWT schedule',
  320: 'Explore Sports Park',
  321: 'Visit the Main Stage',
  322: 'Visit the Breakout Stages',
  323: 'Access the Tech Crawl',
  324: 'Wear a crazy pair of socks',
  325: 'Join an impromptu karaoke session',
  326: 'Start a conga line',
  327: 'Take a goofy group photo',
  328: 'Share a fun fact',
  329: 'Draw a doodle of someone',
  330: 'Doodle on a napkin',
  331: 'Trade swag with someone',
  332: 'Spot a Kamala Harris t-shirt',
  333: 'Create a Summit-inspired dance',
};

export default phrases;
