import { Phrases } from '../types';

const phrases: Phrases = {
  1: 'Someone is wearing a unique shirt',
  2: '"I think what you said is..."',
  3: '“lots of love in the comments"',
  4: '“I wish we had more time”',
  5: 'Someone has a unique virtual background',
  6: 'Someone has a unique virtual background​',
  7: '“Put your questions in the comments”​',
  8: 'Meeting finishes on time​',
  9: 'Someone breaks out into dance​',
  10: '“Can you hear me now?​',
  11: '“A little bit about me”​',
  12: 'Cough or sneeze​',
  13: '“Pride”​',
  14: 'You spot a pet​',
  15: '“What’s your career?”​',
  16: '“Can you see my screen?”​',
  17: '“Thank you for joining us”​',
  18: 'Somone one uses the pride flag emoji​',
  19: '“On the main stage”​',
  20: '“Our next speaker is…”​',
  21: '“Before we start”​',
  22: 'Someone was on mute​',
  23: 'Verbal description of themselves',
  24: "“I'd like to introduce...”​",
  25: 'Coffee mug',
  26: 'Pride Flag',
  27: '“Give it up for…”​',
  28: '1st time at LWT event​',
  29: 'Meet someone new​',
  30: 'LWT intro video',
  31: 'Music',
  32: 'LWT swag spotted',
  33: 'Select the “Connect” button in Speed Networking​',
  34: '“Join us next year”​',
  35: 'Learn something new',
  36: 'Talk to someone advanced in their field​',
  37: 'Dancing',
  38: `Got someone's LinkedIn`,
  39: 'Squad Jobs',
  40: 'Text someone about LWT',
  41: 'See a wedding ring',
  42: 'Someone complements another person',
  43: 'Find someone you know',
  44: 'Real background',
  45: 'Make a new friend',
  46: 'Talk to someone starting their career',
  47: 'Strategic initiative',
  48: 'Technical difficulties during speed networking',
};

export default phrases;
